name: taskforce_hrms
description: A system of human resources managment system using Flutter, Firebase and Pythin for AI.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter_bloc: ^8.1.3
  google_fonts: ^5.1.0
  firebase_storage: ^11.2.6
  loading_animation_widget: ^1.2.0+4
  animated_bottom_navigation_bar: ^1.2.0
  #  awesome_snackbar_content: ^0.1.3
  #  shared_preferences: ^2.2.0
  flutter_icon_snackbar: ^1.1.4
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  introduction_screen: ^3.1.11
  url_launcher: ^6.1.12
  dart_secure: ^0.5.0
  line_icons: ^2.0.3


dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.2
  local_auth: ^2.1.6


flutter_icons:
  android: true
  ios: true
  image_path: "assets/TFLogo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/TFLogo.jpg
    - assets/logoTransparent.png
